services:
  - type: web
    name: qms-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi_entry:application --preload --timeout 120
    postDeployCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput || true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: CSRF_TRUSTED_ORIGINS
        value: ""
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: qms-db
          property: connectionString
    autoDeploy: true

databases:
  - name: qms-db
    plan: free
